# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-DeepAbstractSearchPager
version:      0.02
version_from: lib/Class/DBI/Plugin/DeepAbstractSearchPager.pm
installdirs:  site
requires:
    Class::DBI:                    0.96
    Class::DBI::Plugin:            0.02
    Class::DBI::Plugin::DeepAbstractSearch: 0.08
    Test::More:                    0.32
    UNIVERSAL::require:            0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
