# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-DeepAbstractSearchPager
version:      0.01
version_from: DeepAbstractSearchPager.pm
installdirs:  site
requires:
    Class::DBI::Plugin:            0.02
    Class::DBI::Plugin::DeepAbstractSearch: 0.02
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
